# Generated by Django 4.0.3 on 2022-03-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_game_genre_name_remove_game_similar_games_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
    ]
