# Generated by Django 4.0.3 on 2022-03-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_rename_game_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_name',
            new_name='name',
        ),
    ]
